name: Exemple d'utilisation du composant Airflow DAG CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-workflow:
    # uses: ../template/.github/workflows/component.yml@main
    uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
    with:
      SFTP_HOST: "sftp.example.com"
      SFTP_USERNAME: "user"
      SFTP_PORT: "22"
      SFTP_DAGS_PATH: "/remote/dags"
    secrets:
      SFTP_PASSWORD: "password"
